import NextLink from 'next/link'
import { Container, FormControl, Link } from '@mui/material'

import './globals.css'

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: {
	children: React.ReactNode
}) {
	return (
		<html lang="en">
			<body>
				<header>
					<Container>
						<FormControl
							sx={{
								display: 'flex',
								flexDirection: 'row',
								columnGap: '2rem',
								padding: '2rem 0 0',
							}}
						>
							<NextLink href="/">
								<Link component="button">Home</Link>
							</NextLink>
							<NextLink href="/posts/create">
								<Link component="button">Create post</Link>
							</NextLink>
						</FormControl>
					</Container>
				</header>
				<main>{children}</main>
			</body>
		</html>
	)
}
